<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function instagram_block_menu() {
  $items['admin/config/content/instagram_block'] = array(
    'title' => 'Instagram Block',
    'description' => 'Configuration page for Instagram Block.',
    'access callback' => TRUE,
    'router_name' => 'block_admin_config_form',
  );

  return $items;
}

/**
 * Theme implementation to output the instagram images.
 */
function theme_instagram_block_image($variables) {
  $element = $variables['element'];
  $output = '
    <a class="group" target="blank_" rel="group1" href="' . $element['link'] . '">
      <img style="float: left; display: inline-block; margin: 0 5px 5px 0px; width: ' . $element['width'] . 'px; height: ' . $element['height'] . 'px;" src="' . $element['url'] . '">
    </a>';

  return $output;
}

/**
 * Implements hook_theme().
 */
function instagram_block_theme() {
  $items = array(
    'instagram_block_image' => array(
      'render element' => 'element',
    ),
  );

  return $items;
}